  
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13-qYWm_iQKcMYMpl69nGQCIUnnYSZalF
"""



import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten


# Charger un dataset d'images (par exemple, MNIST)
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# Préparer les données
# ...

# Créer le modèle
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compiler le modèle
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Entraîner le modèle
model.fit(x_train, y_train, epochs=5)

# Évaluer le modèle

test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)
